### ISSUE TITLE
Addon not installing Blender 3.0.0

### ISSUE THREAD

**Issue by edin45** [Gorgious56/asset_browser_utilities#35]
Hello there,

When i try to install the addon i get this issue:
![Screenshot from 2022-01-27 11-26-48](https://user-images.githubusercontent.com/48309852/151330668-e480b631-e743-457c-b5fd-e1460566a9d4.png)

Am I doing something wrong?

**Comment by Gorgious56** [comment]
Nope, you did nothing wrong, that's just a problem with github messing with the zip file name. You have two solutions :
- Download the latest release and re-install the addon (recommended since it's more stable) : https://github.com/Gorgious56/asset_browser_utilities/releases
- Rename the zip you downloaded and remove `-master` at the end of the zip file, remove the addon from blender, then re-enable it.

Hope it helps !

Cheers

**Comment by edin45** [comment]
Thanks a lot! It works now.

**Comment by KelvinLaw-jpg** [comment]
Hi, I tried to install the latest version of the add on (0.2.4) to blender 3.5 and 3.6. The same problem occurred, also tried to rename the zipp file and reinstalling it, also didn't work. Thanks!
![Capture](https://github.com/Gorgious56/asset_browser_utilities/assets/73468336/d541a5de-4a5e-4cc4-b16a-cedd1fcabc8c)

**Comment by KelvinLaw-jpg** [comment]
Problem solved, for windows user, you will need to go to your "C:\Users\ {YOUR OWN USER NAME} \AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons" and rename the file name to "asset_browser_utilities"

**Comment by Shaddy-ElDesouky** [comment]
On Linux and should be the same on any OS, change folder name inside archive, remove" -master" re zip it again
