### ISSUE TITLE
Hi! Won't you help a little? Thank you

### ISSUE THREAD

**Issue by MuhammadXr** [Gorgious56/asset_browser_utilities#41]
I saw that you have experience in checking all subfolders and importing obj from it.

I need a code that searches and imports fbx from all the subfolders in the selected folder. Can you share if you know?

**Comment by MuhammadXr** [comment]
Or the address of the question is here:

https://blender.stackexchange.com/questions/255589/batch-import-fbx-from-all-subfolders-with-filename-script-in-blender

**Comment by Gorgious56** [comment]
Hello again, Sorry Im going to close this since it's a channel for issues pertaining to the code of the addon, not for gathering information. You can study the code if you want but it's specifically designed for asset data so it might not translate well to other file formats. Ill take a look at your question on stack exchange later though. Cheers
