### ISSUE TITLE
Batch (re)move from catalogs has no an empty imput list for the catalog values

### ISSUE THREAD

**Issue by Intuos5** [Gorgious56/asset_browser_utilities#43]
![afbeelding](https://user-images.githubusercontent.com/63149655/164042945-93a728eb-39ff-4d9a-b8c2-8e68035e9485.png)

All catalog moving/ removing operations suffer from the same issue that they have no input values to choose from. These values can also not be typed in. This happens when trying to change catalogs for files on disk in Blender 3.1.

![afbeelding](https://user-images.githubusercontent.com/63149655/164042832-5cc06e2f-75b6-4cda-84ec-0670dafb4710.png)

**Comment by Gorgious56** [comment]
Yeah this is an issue I'd want to fix, and thanks for bringing it up ! 
I have to say that I don't 100% yet completely understand the design philosophy between catalogs in the asset browser. The actual information regarding catalogs is stored in a .txt file inside the folder of the library. But if you have several files in the library in different folders, not all of them will also have an associated .txt catalog definition file in their folder. But they do seem to read it though since you'll have access to catalogs inside Blender, even for files that are not in the target library's folder. 
It's complicated and unreliable, I wish they'll implement an easier way to get these informations.

It's not as easy as letting the user input a name either, since catalogs are referenced by UUID and two different catalogs can share the same name but not the same UUID. The UUID definition is located inside the .txt definition file, which may or may not be inside that particular .blend library file's folder ><

I'll poke around and see how to fix this in the meantime.

Cheers

**Comment by Intuos5** [comment]
For me this is also a little confusing. When editing a catalog, it needs to be edited within an asset file. The asset file needs to be saved in order to change a catalog name or to add a catalog name. I think this is something you can ask the developers over on https://blender.chat/channel/asset-project. By now, they are fully aware of your addon and it's been posted a couple of times in the chat recently.

**Comment by Intuos5** [comment]
Though sofar, upon further inspection, I can only see the .txt file in the main library folder. I think that the .txt only stores the catalog paths and UUID. The assets themselves probably have a datablock with this same UUID associated, which is how Blender nows to which catalog it is associated.
I think that the catalog names can be changed, because the UUID is a constant. The assetbrowser probably requires storing the file to be able to check whether it corresponds to an existing UUID + name, if not it adds a new catalog to the list. In case the UUID is found, but has a different name, it updates the name associated to the UUID. That would at least explain why it works the way it does.

**Comment by Gorgious56** [comment]
Yes indeed, each item that has been marked as an asset has a string field associated with it that can contain its catalog UUID : https://docs.blender.org/api/current/bpy.types.AssetMetaData.html#bpy.types.AssetMetaData.catalog_id
It also means one asset can only be part of one catalog, unfortunately.

The thing I have yet to determine is where exactly is the "main library" catalog definition file stored and how it is accessed, and what happens when catalogs are defined in several files, what happens when you merge two libraries with different catalog definitions files, what happens in the process if there is a UUID collision between two catalogs, what file is saved when you save a blend file from a library with no catalog file in its folder but several other catalogs in the whole library, etc :)

Now that I think of it, I added a commit recently to search for catalogs in parent folders (https://github.com/Gorgious56/asset_browser_utilities/commit/18703abc4c2e888721768d301e961fbb5c92706b), maybe I should also add a way to search for catalogs in child folders. I'm a bit concerned about performance on big libraries though, I should test this out. 

Yes catalog names can be changed non-destructively since they keep the same UUID, but on the other hand you can't rely on a catalog name to find its corresponding UUID because it's not a 1-1 relationship, like we have in object names in blender for instance.

An option to add a new catalog if it doesn't exist seems like a nice feature, I've added it to the todo : https://github.com/Gorgious56/asset_browser_utilities/issues/45

**Comment by Gorgious56** [comment]
AFAIK this is not solved in latest version, I'll try to tackle it for the next one.
