### ISSUE TITLE
Perhaps add studio setup for previews [IDEA]

### ISSUE THREAD

**Issue by schroef** [Gorgious56/asset_browser_utilities#59]
Found your asset utils through the cutaway shader of the BlenderBIM. I also bumped into this studio light setup file. Perhaps would be nice if such a thing, or this one could be added in the process. Would allow for nicer thumbnails.

Its not using any HDR, but could use very simple small one. Guess it would need extra code so the object or studio will be scaled to the studio size or visa versa

https://ibotpl.gumroad.com/l/studiolighting

![image](https://public-files.gumroad.com/tifsqpvvhgafr3fa04do0xkey8sl)

**Comment by Gorgious56** [comment]
Thank you for your input :)

Yeah it would be nice and I think that would be an awesome feature, but I think custom lighting setups and render scenes will be implemented in vanilla blender by the devs down the line, so I set this goal to low priority right now since it would take a lot of efforts and will be clunky at best considering the limitations of the python API...

**Comment by schroef** [comment]
Aha i see, didi knew they were thinking about that

**Comment by Gorgious56** [comment]
After some thought I don't intend to support this kind of feature, it's a bit too much work and I fear feature creep. Also as mentioned I count on blender devs to make something like that in the future so we'll see. 

Sorry !

Cheers

**Comment by schroef** [comment]
I can always make a custom edit in your addon and keep it for myself
