### ISSUE TITLE
Rename asset as blend and object data properties 

### ISSUE THREAD

**Issue by 3DonkeyKings** [Gorgious56/asset_browser_utilities#91]
So both work only in Current file for me not in the other modes.

But what's weird is that I cant get it to work that asset name and object data properties have the same name

Tried different combinations to get both renamed as .blend/asset name and names doesn't match
When taking the .blend name to rename for both it works the closest but the .001,002,.. don't match, it picks them randomly

When naming asset as blend and data properties as asset, it doesn't work at all

Can live with it but it would be nice if you take a look into it

---

So I´ve gone through some more files, the random .001,002.. only seem to happen occasionly on files with a lot of assets, but I cannot reproduce it easily.
I´m using the method below now and it works quite well.

**Comment by KoenigDerEsel** [comment]
What actually would aid me more is if I could make a preset like this:
![image](https://user-images.githubusercontent.com/91736745/184525686-4d4f099d-2cd1-42a6-b00f-50b7bad9e152.png)

**Comment by Gorgious56** [comment]
Yeah this system can't be 100% reliable because of the way renaming works in Blender. I would suggest you enable "Same as Asset" as that would rename the data as the asset name, but there are instances where it will fail.

eg if you already have a data somewhere in the file with the same name as your blend file name, renaming the asset would work but then trying to rename the data as the file name will fail and add a .001 at the end, and all the other ones will be out of sync.

Custom operations are not yet supported by the preset system but I intend to work on making it so :)

**Comment by KoenigDerEsel** [comment]
Ok, thanks for putting it onto your list :)

So I´ve tried to rename same as asset for data properties a bit more extensively, I simply couldnt get it to work.
How can I get it to sync?
I mean saving/reopening the files doesnt help at all.

It would definetly be useful in cases where I use naming differing from the blendname

**Comment by Gorgious56** [comment]
You're absolutely right, this was buggy and never should have worked. I [fixed it](https://github.com/Gorgious56/asset_browser_utilities/commit/13d26f9e7154d6356158670c27ad9e5c1c621535), hopefully it should work now :)

You can try it by using the dev version if you know how to (download the github repo as a zip, and rename it by removing `-master` from the name before activating the addon), or it will be available in hte next release once I add a little more features to this version.

Cheers !

**Comment by KoenigDerEsel** [comment]
Yeah I already know, but thanks for explaining, I´ll try the new version :)

If it works, the addon should fulfill my needs already at a level at which I can work through my backlog of assets quite easily, but if you want, I can test out more of its functions and post any issues.
Doesnt matter to me when, I´ll gladly help out, but you know better when the time is appropriate and if you need it.

**Comment by KoenigDerEsel** [comment]
So just to confirm, works perfectly fine when it´s the only custom operation that references the asset name.

In a combination like in the image I posted, it gets confused, but that´s apparently how things work for now.

I mean to do it in 2 steps now is also working, so one operation to mark and name as .blend file and then the second to rename data, but there might be a possibility for you to let the script rerun after the first custom operation finishes renaming.

**Comment by Gorgious56** [comment]
Hehe I value your feedback a lot because usually I find out the bugs for the specific workflows I need the addon for, but there are some features I never use so I'm glad you bring it up. please don't hesitate, I'll add it to the backlog and it will speed up my bugfixing sessions afterwards ;)

The problem may be because the order in which the assets are operated on is non deterministic for performance reason, so the asset and asset data may not be traversed in the same order. But it might also be another bug lurking in the corner >< I'll see what I can do to fix it !

**Comment by Gorgious56** [comment]
Quick update : I've removed the "Custom Operation" from all other tools and it's now only available in its own submenu, it was too buggy to keep it like that.

![image](https://user-images.githubusercontent.com/25156105/198899784-d2318581-a54a-40f2-9ecf-cfd9b84e2fd2.png)

You can however now apply the operations asset per asset, instead of per batches. i hope it fixes your problem.

![image](https://user-images.githubusercontent.com/25156105/198899775-12ef7432-f5f9-4064-b2cc-bcdded68cf82.png)

FWIW I plan on releasing the new features soon, tomorrow or the day after.

Cheers

**Comment by 3DonkeyKings** [comment]
Appreciated, I've got some assets waiting for a try  :)

**Comment by Intuos5** [comment]
Hi @Gorgious56 are you planning to reintroduce the batch renaming for external folders? I have got a library that is in dire need of renaming with Prefixes and Suffixes. 
I don't understand why some commercial addons have such generic naming schemes :(
